# Generated by Django 3.0.8 on 2020-08-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trunc_year', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='type',
            field=models.CharField(choices=[('', 'Lack of information'), ('donation', 'Donation'), ('grant', 'Grant')], default='donation', max_length=256, verbose_name='Type'),
        ),
    ]
