# Generated by Django 3.0.8 on 2020-08-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trunc_year', '0003_donation_donation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationReport',
            fields=[
            ],
            options={
                'verbose_name': 'Donation Report',
                'verbose_name_plural': 'Donation Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trunc_year.donation',),
        ),
    ]
