# Generated by Django 3.1 on 2020-08-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trunc_year', '0004_donationreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationreport',
            options={'verbose_name': 'Donations Report', 'verbose_name_plural': 'Donations Reports'},
        ),
    ]
