# Generated by Django 3.0.8 on 2020-07-20 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokeInstituteVisits',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrance', models.DateTimeField(blank=True, verbose_name='Entrance')),
            ],
            options={
                'verbose_name': 'PokeInstitute Visit',
                'verbose_name_plural': 'PokeInstitute Visits',
                'ordering': ('-entrance',),
            },
        ),
    ]
