# Generated by Django 3.0.8 on 2020-07-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trunc_day', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokeInstituteVisitsReport',
            fields=[
            ],
            options={
                'verbose_name': 'PokeInstitute Visits Report',
                'verbose_name_plural': 'PokeInstitute Visits Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trunc_day.pokeinstitutevisits',),
        ),
    ]
