# Generated by Django 3.1 on 2020-08-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_go_vs_express', '0002_yearroundemployerexpenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
