# Generated by Django 3.1 on 2020-08-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_go_vs_express', '0003_employee_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearRoundEmployerExpensesReport',
            fields=[
            ],
            options={
                'verbose_name': 'Employer Expenses Report',
                'verbose_name_plural': 'Employer Expenses Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('plotly_go_vs_express.yearroundemployerexpenses',),
        ),
    ]
